/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package attendance_ms;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author hp
 */
public class Home extends javax.swing.JFrame {

    Attendance_MS db = new Attendance_MS();

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        date_lbl.setText(Attendance_MS.showDate());
        sTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        header_panel = new javax.swing.JPanel();
        admin_btn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        time_lbl = new javax.swing.JLabel();
        date_lbl = new javax.swing.JLabel();
        signin_btn = new javax.swing.JLabel();
        footer_panel = new javax.swing.JPanel();
        signin_panel = new javax.swing.JPanel();
        jSeparator6 = new javax.swing.JSeparator();
        nametxt = new javax.swing.JTextField();
        name_lbl = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        statustxt = new javax.swing.JTextField();
        status_lbl = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        depttxt = new javax.swing.JTextField();
        unit_lbl = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        image_lbl = new javax.swing.JLabel();
        signout_btn = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        passtxt = new javax.swing.JTextField();
        btn9 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        enter_btn = new javax.swing.JButton();
        cancel_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        unit_lbl1 = new javax.swing.JLabel();
        gendertxt = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        signinin_btn = new javax.swing.JButton();
        admin_panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        fullname_txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(240, 244, 240));
        jPanel2.setToolTipText("");
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header_panel.setBackground(new java.awt.Color(33, 63, 86));
        header_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        admin_btn.setBackground(new java.awt.Color(33, 63, 86));
        admin_btn.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        admin_btn.setForeground(new java.awt.Color(255, 255, 255));
        admin_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        admin_btn.setText("admin panel");
        admin_btn.setOpaque(true);
        admin_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                admin_btnMouseClicked(evt);
            }
        });
        header_panel.add(admin_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 210, 30));

        jLabel1.setBackground(new java.awt.Color(255, 51, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 244, 240));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("x");
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel1MouseMoved(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        header_panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 10, 30, 30));

        time_lbl.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        time_lbl.setForeground(new java.awt.Color(255, 255, 255));
        header_panel.add(time_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 270, 50));

        date_lbl.setFont(new java.awt.Font("Yu Mincho Demibold", 1, 18)); // NOI18N
        date_lbl.setForeground(new java.awt.Color(255, 255, 255));
        header_panel.add(date_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, 270, 50));

        signin_btn.setBackground(new java.awt.Color(22, 42, 57));
        signin_btn.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        signin_btn.setForeground(new java.awt.Color(255, 255, 255));
        signin_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signin_btn.setText("Sign In");
        signin_btn.setOpaque(true);
        signin_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signin_btnMouseClicked(evt);
            }
        });
        header_panel.add(signin_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 210, 30));

        jPanel2.add(header_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 240));

        footer_panel.setLayout(new java.awt.CardLayout());

        signin_panel.setBackground(new java.awt.Color(250, 242, 240));
        signin_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator6.setBackground(new java.awt.Color(102, 102, 102));
        signin_panel.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 920, 10));

        nametxt.setEditable(false);
        nametxt.setBackground(new java.awt.Color(32, 33, 35));
        nametxt.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        nametxt.setForeground(new java.awt.Color(255, 255, 255));
        signin_panel.add(nametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 390, 30));

        name_lbl.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        name_lbl.setForeground(new java.awt.Color(57, 113, 177));
        name_lbl.setText("Name");
        signin_panel.add(name_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 170, -1));

        jSeparator7.setBackground(new java.awt.Color(102, 102, 102));
        signin_panel.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 340, 10));

        statustxt.setEditable(false);
        statustxt.setBackground(new java.awt.Color(32, 33, 35));
        statustxt.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        statustxt.setForeground(new java.awt.Color(255, 255, 255));
        signin_panel.add(statustxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 390, 30));

        status_lbl.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        status_lbl.setForeground(new java.awt.Color(57, 113, 177));
        status_lbl.setText("Status");
        signin_panel.add(status_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 170, -1));

        jSeparator8.setBackground(new java.awt.Color(102, 102, 102));
        signin_panel.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 260, 10));

        depttxt.setEditable(false);
        depttxt.setBackground(new java.awt.Color(32, 33, 35));
        depttxt.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        depttxt.setForeground(new java.awt.Color(255, 255, 255));
        signin_panel.add(depttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 390, 30));

        unit_lbl.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        unit_lbl.setForeground(new java.awt.Color(57, 113, 177));
        unit_lbl.setText("Department");
        signin_panel.add(unit_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 170, -1));

        jSeparator9.setBackground(new java.awt.Color(102, 102, 102));
        signin_panel.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 270, 140, 20));

        image_lbl.setBackground(new java.awt.Color(255, 255, 255));
        image_lbl.setOpaque(true);
        signin_panel.add(image_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 70, 180, 190));

        signout_btn.setBackground(new java.awt.Color(33, 63, 88));
        signout_btn.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        signout_btn.setForeground(new java.awt.Color(255, 255, 255));
        signout_btn.setText("Sign Out");
        signout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signout_btnActionPerformed(evt);
            }
        });
        signin_panel.add(signout_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, 130, 30));

        jSeparator10.setBackground(new java.awt.Color(102, 102, 102));
        signin_panel.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 170, 10));

        jSeparator11.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator11.setOrientation(javax.swing.SwingConstants.VERTICAL);
        signin_panel.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 90, 10, 160));

        passtxt.setEditable(false);
        passtxt.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        passtxt.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        passtxt.setBorder(null);
        signin_panel.add(passtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 250, 60));

        btn9.setFont(new java.awt.Font("Yu Mincho Light", 0, 24)); // NOI18N
        btn9.setText("9");
        btn9.setBorder(null);
        btn9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn9MouseClicked(evt);
            }
        });
        signin_panel.add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 50, 50));

        btn8.setFont(new java.awt.Font("Yu Mincho Light", 0, 24)); // NOI18N
        btn8.setText("8");
        btn8.setBorder(null);
        btn8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn8MouseClicked(evt);
            }
        });
        signin_panel.add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 50, 50));

        btn7.setFont(new java.awt.Font("Yu Mincho Light", 0, 24)); // NOI18N
        btn7.setText("7");
        btn7.setBorder(null);
        btn7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn7MouseClicked(evt);
            }
        });
        signin_panel.add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 50, 50));

        btn4.setFont(new java.awt.Font("Yu Mincho Light", 0, 24)); // NOI18N
        btn4.setText("4");
        btn4.setBorder(null);
        btn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn4MouseClicked(evt);
            }
        });
        signin_panel.add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 50, 50));

        btn5.setFont(new java.awt.Font("Yu Mincho Light", 0, 24)); // NOI18N
        btn5.setText("5");
        btn5.setBorder(null);
        btn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn5MouseClicked(evt);
            }
        });
        signin_panel.add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 50, 50));

        btn6.setFont(new java.awt.Font("Yu Mincho Light", 0, 24)); // NOI18N
        btn6.setText("6");
        btn6.setBorder(null);
        btn6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn6MouseClicked(evt);
            }
        });
        signin_panel.add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 50, 50));

        btn0.setFont(new java.awt.Font("Yu Mincho Light", 0, 24)); // NOI18N
        btn0.setText("0");
        btn0.setBorder(null);
        btn0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn0MouseClicked(evt);
            }
        });
        signin_panel.add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 50, 50));

        btn2.setFont(new java.awt.Font("Yu Mincho Light", 0, 24)); // NOI18N
        btn2.setText("2");
        btn2.setBorder(null);
        btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn2MouseClicked(evt);
            }
        });
        signin_panel.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 50, 50));

        btn1.setFont(new java.awt.Font("Yu Mincho Light", 0, 24)); // NOI18N
        btn1.setText("1");
        btn1.setBorder(null);
        btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn1MouseClicked(evt);
            }
        });
        signin_panel.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 50, 50));

        btn3.setFont(new java.awt.Font("Yu Mincho Light", 0, 24)); // NOI18N
        btn3.setText("3");
        btn3.setBorder(null);
        btn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn3MouseClicked(evt);
            }
        });
        signin_panel.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 50, 50));

        enter_btn.setFont(new java.awt.Font("Yu Mincho Light", 0, 14)); // NOI18N
        enter_btn.setText("ENTER");
        enter_btn.setBorder(null);
        enter_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enter_btnActionPerformed(evt);
            }
        });
        signin_panel.add(enter_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 60, 40));

        cancel_btn.setFont(new java.awt.Font("Dotum", 0, 14)); // NOI18N
        cancel_btn.setText("C");
        cancel_btn.setBorder(null);
        cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btnActionPerformed(evt);
            }
        });
        signin_panel.add(cancel_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 60, 40));
        signin_panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 300, 340));

        unit_lbl1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        unit_lbl1.setForeground(new java.awt.Color(57, 113, 177));
        unit_lbl1.setText("Gender");
        signin_panel.add(unit_lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 170, -1));

        gendertxt.setEditable(false);
        gendertxt.setBackground(new java.awt.Color(32, 33, 35));
        gendertxt.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        gendertxt.setForeground(new java.awt.Color(255, 255, 255));
        signin_panel.add(gendertxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 390, 30));

        jSeparator12.setBackground(new java.awt.Color(102, 102, 102));
        signin_panel.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 90, 10));

        signinin_btn.setBackground(new java.awt.Color(33, 63, 88));
        signinin_btn.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        signinin_btn.setForeground(new java.awt.Color(255, 255, 255));
        signinin_btn.setText("Sign In");
        signinin_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinin_btnActionPerformed(evt);
            }
        });
        signin_panel.add(signinin_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 130, 30));

        footer_panel.add(signin_panel, "card2");

        admin_panel.setBackground(new java.awt.Color(250, 242, 240));
        admin_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(57, 113, 177));
        jLabel3.setText("UserName");
        admin_panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 80, -1));

        jSeparator1.setBackground(new java.awt.Color(102, 102, 102));
        admin_panel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 500, 10));

        jPasswordField1.setBackground(new java.awt.Color(32, 33, 35));
        jPasswordField1.setForeground(new java.awt.Color(57, 113, 177));
        jPasswordField1.setText("password");
        jPasswordField1.setCaretColor(new java.awt.Color(255, 255, 255));
        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusGained(evt);
            }
        });
        jPasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPasswordField1MouseExited(evt);
            }
        });
        admin_panel.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 390, 30));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 52, 54));
        jLabel4.setText("Password");
        admin_panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 90, -1));

        jButton1.setBackground(new java.awt.Color(33, 63, 88));
        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Sign In");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        admin_panel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 280, 40));

        jSeparator2.setBackground(new java.awt.Color(102, 102, 102));
        admin_panel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 920, 10));

        jSeparator4.setBackground(new java.awt.Color(102, 102, 102));
        admin_panel.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 610, 10));

        jSeparator5.setBackground(new java.awt.Color(102, 102, 102));
        admin_panel.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 500, 10));

        fullname_txt.setBackground(new java.awt.Color(32, 33, 35));
        fullname_txt.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        fullname_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fullname_txtFocusGained(evt);
            }
        });
        fullname_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fullname_txtMouseClicked(evt);
            }
        });
        fullname_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fullname_txtKeyTyped(evt);
            }
        });
        admin_panel.add(fullname_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 390, 30));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon80/admini.jpg"))); // NOI18N
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel5.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel5.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel5.setPreferredSize(new java.awt.Dimension(80, 80));
        admin_panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 300, 340));

        footer_panel.add(admin_panel, "card3");

        jPanel2.add(footer_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 1000, 440));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 690));

        setSize(new java.awt.Dimension(1006, 683));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    void sTime() {
        new Timer(0, (ActionEvent e) -> {
            // converted to lambda expression form anonymous inner class by netbean.. i dont know shit about lambda
            time_lbl.setText(Attendance_MS.showTime());
        }).start();
    }
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseMoved
        // TODO add your handling code here:
        jLabel1.setForeground(new Color(255, 0, 0));
    }//GEN-LAST:event_jLabel1MouseMoved

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
        jLabel1.setForeground(new Color(240, 244, 240));
    }//GEN-LAST:event_jLabel1MouseExited
    //------ method to make frames draggable------
    int xx;
    int xy;
    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel2MouseClicked
    // ---End of methods----

//-------- Switching btw label colors on click of buttons------------//
    private void signin_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signin_btnMouseClicked
        // TODO add your handling code here:
        setLblColor(admin_btn);
        resetLblColor(signin_btn);
        signin_panel.setVisible(true);
        admin_panel.setVisible(false);
    }//GEN-LAST:event_signin_btnMouseClicked

    private void admin_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admin_btnMouseClicked
        // TODO add your handling code here:
        setLblColor(signin_btn);
        resetLblColor(admin_btn);
        signin_panel.setVisible(false);
        admin_panel.setVisible(true);
    }//GEN-LAST:event_admin_btnMouseClicked

    private void jPasswordField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusGained
        // TODO add your handling code here:
        jLabel4.setForeground(new Color(57, 113, 197));

        jLabel3.setForeground(new Color(51, 52, 54));


    }//GEN-LAST:event_jPasswordField1FocusGained

    private void jPasswordField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MouseClicked
        // TODO add your handling code here:
        jPasswordField1.setText("");
        jPasswordField1.setForeground(new Color(255, 250, 255));
    }//GEN-LAST:event_jPasswordField1MouseClicked

    private void jPasswordField1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MouseExited

    }//GEN-LAST:event_jPasswordField1MouseExited

    private void fullname_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fullname_txtMouseClicked
        fullname_txt.setText("");
        fullname_txt.setForeground(new Color(255, 250, 255));
    }//GEN-LAST:event_fullname_txtMouseClicked

    private void fullname_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fullname_txtKeyTyped
        // TODO add your handling code here:
        fullname_txt.setForeground(new Color(255, 250, 255));
    }//GEN-LAST:event_fullname_txtKeyTyped

    private void fullname_txtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fullname_txtFocusGained
        // TODO add your handling code here:
        jLabel3.setForeground(new Color(57, 113, 197));

        jLabel4.setForeground(new Color(51, 52, 54));
    }//GEN-LAST:event_fullname_txtFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        new Admin().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void signout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signout_btnActionPerformed
        // TODO add your handling code here:
        if (nametxt.getText().length() > 0) {
            try {

                Class.forName("org.sqlite.JDBC");
                Connection conn = DriverManager.getConnection(db.getDB_url(), db.getDB_name(), db.getDB_pass());
                PreparedStatement ps1 = conn.prepareStatement("select * from attendanceTB where name='" + nametxt.getText() + "'", ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
                ResultSet rs = ps1.executeQuery();
                rs.next();
                String timein = rs.getString("time_in");
                PreparedStatement ps = conn.prepareStatement("INSERT INTO reporttb VALUES('" + nametxt.getText() + "','" + depttxt.getText() + "','" + statustxt.getText() + "','" + gendertxt.getText() + "','" + Attendance_MS.showDate() + "','" + timein + "','" + Attendance_MS.showTime() + "')");

                //ps.setInt(1, 1);
                //ps.executeUpdate();
                if (ps.executeUpdate() == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Sign Out successful");

                    ///PreparedStatement ps2 = conn.prepareStatement("delete * from attendanceTB where name='" + nametxt.getText() + "'");
                    //ps2.executeUpdate();
                    // Statement stat = conn.createStatement();
                    //stat = conn.createStatement();
                    rs.deleteRow();
                    ps1.close();
                    db.clearText(nametxt);
                    db.clearText(statustxt);
                    db.clearText(depttxt);
                    db.clearText(gendertxt);
                    db.clearText(passtxt);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Unsuccessful");
                    passtxt.setText("");
                }

                conn.close();
                ps.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "You are not Logged In");
                db.clearText(nametxt);
                db.clearText(statustxt);
                db.clearText(depttxt);
                db.clearText(gendertxt);
                db.clearText(passtxt);
                //e.printStackTrace();

            } catch (ClassNotFoundException ex) {
               // Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
               JOptionPane.showMessageDialog(null, "Error in getting db class, call the admin");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Input Valid Password");
            passtxt.setText("");
        }
    }//GEN-LAST:event_signout_btnActionPerformed

    private void enter_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enter_btnActionPerformed
        // TODO add your handling code here:
        Image image;
        byte[] imageBytes;
        String password = passtxt.getText();
        if (password.length() == 4) {
            try {
                Class.forName("org.sqlite.JDBC");
                Connection conn = DriverManager.getConnection(db.getDB_url(), db.getDB_name(),"");
                PreparedStatement ps = conn.prepareStatement("select * from detailsTB where password='" + passtxt.getText() + "'");
                //ps.setInt(1, 1);
                ResultSet rs = ps.executeQuery();
                rs.next();
                //imageBytes = rs.getBytes(1);
                
                
                // imagelbl.setIcon(icon);
                byte [] pic = null;
                nametxt.setText(rs.getString("name"));
                statustxt.setText(rs.getString("status"));
                depttxt.setText(rs.getString("unit"));
                gendertxt.setText(rs.getString("gender"));
                String imageURL = rs.getString("image");
                image_lbl.setIcon(db.ResizeImage(imageURL, pic, image_lbl));
                /*image = getToolkit().createImage(imageBytes);
                ImageIcon icon = new ImageIcon(image);
                image_lbl.setIcon(icon);*/
                passtxt.setText("");
                conn.close();
                if (gendertxt.getText().equals("male")) {
                    JOptionPane.showMessageDialog(null, "Welcome, Mr " + nametxt.getText());

                } else if (gendertxt.getText().equals("female")) {
                    JOptionPane.showMessageDialog(null, "Welcome, Madam " + nametxt.getText());
                }

                conn.close();
                ps.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e);

                db.clearText(nametxt);
                db.clearText(statustxt);
                db.clearText(depttxt);
                db.clearText(passtxt);

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {

            JOptionPane.showMessageDialog(null, "password should be four digits");
            db.clearText(passtxt);

        }

    }//GEN-LAST:event_enter_btnActionPerformed

    private void cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_btnActionPerformed
        // TODO add your handling code here:
        db.clearText(passtxt);
    }//GEN-LAST:event_cancel_btnActionPerformed

    private void signinin_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinin_btnActionPerformed
        // TODO add your handling code here:
        if (nametxt.getText().length() > 0) {
            try {

                //Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/attendancedb", "root", "timmy");
                PreparedStatement ps = conn.prepareStatement("INSERT INTO attendanceTB VALUES('" + nametxt.getText() + "','" + depttxt.getText() + "','" + statustxt.getText() + "','" + gendertxt.getText() + "','" + Attendance_MS.showDate() + "','" + Attendance_MS.showTime() + "')");

                //ps.setInt(1, 1);
                //ps.executeUpdate();
                if (ps.executeUpdate() == 1) {
                    JOptionPane.showMessageDialog(rootPane, "You are Signed In");
                    db.clearText(nametxt);
                    db.clearText(statustxt);
                    db.clearText(depttxt);
                    db.clearText(gendertxt);
                    db.clearText(passtxt);
                    image_lbl.setIcon(null);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Unsuccessful");
                    passtxt.setText("");
                }
                conn.close();
                ps.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Already Logged In");
                db.clearText(nametxt);
                db.clearText(statustxt);
                db.clearText(depttxt);
                db.clearText(gendertxt);
                db.clearText(passtxt);
                image_lbl.setIcon(null);
                //e.printStackTrace();

            }
        } else {
            JOptionPane.showMessageDialog(null, "Input Valid Password");
            db.clearText(passtxt);
        }

    }//GEN-LAST:event_signinin_btnActionPerformed

    private void btn9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn9MouseClicked
        passtxt.setText(passtxt.getText() + "9");
    }//GEN-LAST:event_btn9MouseClicked

    private void btn8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn8MouseClicked
        passtxt.setText(passtxt.getText() + "8");
    }//GEN-LAST:event_btn8MouseClicked

    private void btn7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn7MouseClicked
        passtxt.setText(passtxt.getText() + "7");
    }//GEN-LAST:event_btn7MouseClicked

    private void btn4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn4MouseClicked
        passtxt.setText(passtxt.getText() + "4");
    }//GEN-LAST:event_btn4MouseClicked

    private void btn5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5MouseClicked
        passtxt.setText(passtxt.getText() + "5");
    }//GEN-LAST:event_btn5MouseClicked

    private void btn6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn6MouseClicked
        passtxt.setText(passtxt.getText() + "6");
    }//GEN-LAST:event_btn6MouseClicked

    private void btn0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn0MouseClicked
        passtxt.setText(passtxt.getText() + "0");
    }//GEN-LAST:event_btn0MouseClicked

    private void btn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MouseClicked
        passtxt.setText(passtxt.getText() + "2");
    }//GEN-LAST:event_btn2MouseClicked

    private void btn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MouseClicked
        passtxt.setText(passtxt.getText() + "3");
    }//GEN-LAST:event_btn3MouseClicked

    private void btn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseClicked
        passtxt.setText(passtxt.getText() + "1");
    }//GEN-LAST:event_btn1MouseClicked
//---------- End --------------

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel admin_btn;
    private javax.swing.JPanel admin_panel;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton cancel_btn;
    private javax.swing.JLabel date_lbl;
    private javax.swing.JTextField depttxt;
    private javax.swing.JButton enter_btn;
    private javax.swing.JPanel footer_panel;
    private javax.swing.JTextField fullname_txt;
    private javax.swing.JTextField gendertxt;
    private javax.swing.JPanel header_panel;
    private javax.swing.JLabel image_lbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel name_lbl;
    private javax.swing.JTextField nametxt;
    private javax.swing.JTextField passtxt;
    private javax.swing.JLabel signin_btn;
    private javax.swing.JPanel signin_panel;
    private javax.swing.JButton signinin_btn;
    private javax.swing.JButton signout_btn;
    private javax.swing.JLabel status_lbl;
    private javax.swing.JTextField statustxt;
    private javax.swing.JLabel time_lbl;
    private javax.swing.JLabel unit_lbl;
    private javax.swing.JLabel unit_lbl1;
    // End of variables declaration//GEN-END:variables

//--------------------methods for setting and resetting label color----------------
    private void setLblColor(JLabel lbl) {
        lbl.setBackground(new Color(33, 63, 86));
    }

    private void resetLblColor(JLabel lbl) {
        lbl.setBackground(new Color(22, 42, 57));
    }
//-----------End methods---------------------------------
}
